# Lab 1 Overview

Objective: (1) Practice hands-on work with the material discussed in lecture 1 (2) To be very familiarized with basic data visualization routines (3) Upon completion of the lab, TA will assist with any questions and homework help

We want you to gain familiarity to be able to complete these task with relative ease as they are very commonplace routines in data science

# ✅ Basic Python

As we discussed in class, there are many types. For this section, please determine by inspection the type and then confirm using the built-in type function

**(6pts)TO DO:** Determine the types using inspection and 'type' 



*   [[2,3,4], [1,2,3],[4,5,6]]
*   (2,3)
*   5.00000001
*   'three'
*   {4,5,6}
*   {'one': 1, 'two': 2, 'three':3}









In [11]:
#list
#tuple
#float
#str
#set
#dict


print(type([[2,3,4], [1,2,3],[4,5,6]]))
print(type((2,3)))
print(type(5.00000001))
print(type('three'))
print(type({4,5,6}))
print(type({'one': 1, 'two': 2, 'three':3}))

<class 'list'>
<class 'tuple'>
<class 'float'>
<class 'str'>
<class 'set'>
<class 'dict'>


We have familiarized ourselves with Python's built-in function, now it is time to practice writing our own functions

**(10pts) TO DO:** Please write a function named "special_list_times". It will take 2 arguments: (1)a list of ints called "int_list" and (2) 1 int called "the_int". The function will return the list with every item multiplied by "the_int"

For example: if int_list = [1,2,3,4,5] and the_int = 2, then [2,4,6,8,10] will be returned

In [12]:
int_list=[1,2,3,4,5]
the_int=2

In [13]:
def special_list_times(int_list,the_int):
    result=[i*the_int for i in int_list]
    print(result)
    
special_list_times(int_list,the_int)

[2, 4, 6, 8, 10]


**(10pts) TO DO:** Given a list of data (ints), we want to write a function that extracts data that meet our condition of being divisible by 6. Then return those that meet the condition into a new list.

For example: if data = [17,13,5,36,30], we only want [36,30]

In [43]:
data=[12,4,10,6,7]

filtered = []

for num in data:
 
    if num % 6 == 0:
        filtered.append(num)
 
print(filtered)

[12, 6]


# ✅ Numpy

**TO DO:** Please import the numpy library with the alias ("nickname") np

In [15]:
import numpy as np

Given the below array of data:





In [16]:
# Given
np.random.seed(1) # Be sure to include this line of code
given_array = np.random.randint(0, high=255, size=(4,5))
given_array

array([[ 37, 235, 140,  72, 137],
       [203, 133,  79, 192, 144],
       [129, 204,  71, 237, 252],
       [134,  25, 178,  20, 254]])

**(6 pts) TO DO:** Using built-in numpy functions, please determine the following:


*   What is the shape of the array?
*   How many items are in this array?
*   What is the sum of all the items in this array?
*   What is the mean of all the items in this array?


*   What is the smallest value in this array?
*   what is the largest value in this array?




In [17]:
np.shape(given_array)

(4, 5)

In [18]:
np.count_nonzero(given_array)

20

In [19]:
np.sum(given_array)

2876

In [20]:
np.mean(given_array)

143.8

In [21]:
np.amin(given_array)

20

In [22]:
np.amax(given_array)

254

**(10pts) TO DO:** built-in numpy functions, please perform the following operations:


*   Scale every item in the array by (item - mean of the entire array)/variance of the entire array [Hint: check out https://numpy.org/doc/stable/reference/generated/numpy.var.html ]
*   Then, reshape this array into a (2,10) array
*   Finally, flatten this array into a 1-dimensional vector



In [26]:
rescale_arrray=(given_array-np.mean(given_array))/np.var(given_array)
print(rescale_array)

[[-1.98754620e-02  1.69723046e-02 -7.07179359e-04 -1.33619679e-02
  -1.26547885e-03]
 [ 1.10171100e-02 -2.00987818e-03 -1.20592691e-02  8.97001187e-03
   3.72199663e-05]
 [-2.75427750e-03  1.12032098e-02 -1.35480677e-02  1.73445043e-02
   2.01360018e-02]
 [-1.82377835e-03 -2.21086600e-02  6.36461423e-03 -2.30391591e-02
   2.05082014e-02]]


In [27]:
np.resize(rescale_array,(2,10))

array([[-1.98754620e-02,  1.69723046e-02, -7.07179359e-04,
        -1.33619679e-02, -1.26547885e-03,  1.10171100e-02,
        -2.00987818e-03, -1.20592691e-02,  8.97001187e-03,
         3.72199663e-05],
       [-2.75427750e-03,  1.12032098e-02, -1.35480677e-02,
         1.73445043e-02,  2.01360018e-02, -1.82377835e-03,
        -2.21086600e-02,  6.36461423e-03, -2.30391591e-02,
         2.05082014e-02]])

In [28]:
rescale_array.flatten()

array([-1.98754620e-02,  1.69723046e-02, -7.07179359e-04, -1.33619679e-02,
       -1.26547885e-03,  1.10171100e-02, -2.00987818e-03, -1.20592691e-02,
        8.97001187e-03,  3.72199663e-05, -2.75427750e-03,  1.12032098e-02,
       -1.35480677e-02,  1.73445043e-02,  2.01360018e-02, -1.82377835e-03,
       -2.21086600e-02,  6.36461423e-03, -2.30391591e-02,  2.05082014e-02])

# ✅ Pandas

**TO DO:** Please import the pandas library with the alias ("nickname") pd

In [7]:
import pandas as pd

We will be working with the comma separated file of the top 50 songs as seen in lecture

**(2 pts) TO DO:** Please read-in this csv file and assign it the name df

In [38]:
df = pd.read_csv('shared/datasets/top50.csv')

Visualizing our data: When working with any dataset, we want to be able to display the data to get a sense of it. For instance, .head() will display the first 5 samples of any dataframe by default.

You can pass in any integer to get another amount of samples (assuming the integer is less than the number of total samples there are in the dataframe)


In [39]:
df.head(5)

TrackName     ArtistName           Genre  \
0                         Señorita   Shawn Mendes    canadian pop   
1                            China       Anuel AA  reggaeton flow   
2    boyfriend (with Social House)  Ariana Grande       dance pop   
3  Beautiful People (feat. Khalid)     Ed Sheeran             pop   
4      Goodbyes (Feat. Young Thug)    Post Malone         dfw rap   

   BeatsPerMinute  Energy  Danceability  LoudnessdB  Liveness  Valence  \
0             117      55            76          -6         8       75   
1             105      81            79          -4         8       61   
2             190      80            40          -4        16       70   
3              93      65            64          -8         8       55   
4             150      65            58          -4        11       18   

   Length  Acousticness  Speechiness  Popularity  
0     191             4            3          79  
1     302             8            9          92  
2     186            12           46          85  
3     198            12           19          86  
4     175            45            7          94

**(6pts) TO DO:** Please display 

*   the first 3 datapoints in this dataframe
*   the last 4 items in this dataframe 
*    a random sample of 3 datapoints in this dataframe

In [40]:
print(df.iloc[:3])

                       TrackName     ArtistName           Genre  \
0                       Señorita   Shawn Mendes    canadian pop   
1                          China       Anuel AA  reggaeton flow   
2  boyfriend (with Social House)  Ariana Grande       dance pop   

   BeatsPerMinute  Energy  Danceability  LoudnessdB  Liveness  Valence  \
0             117      55            76          -6         8       75   
1             105      81            79          -4         8       61   
2             190      80            40          -4        16       70   

   Length  Acousticness  Speechiness  Popularity  
0     191             4            3          79  
1     302             8            9          92  
2     186            12           46          85  


In [41]:
print(df.tail(4))

                                        TrackName        ArtistName    Genre  \
46                                      Te Robaré         Nicky Jam    latin   
47                                        Happier        Marshmello  brostep   
48                                  Call You Mine  The Chainsmokers      edm   
49  Cross Me (feat. Chance the Rapper & PnB Rock)        Ed Sheeran      pop   

    BeatsPerMinute  Energy  Danceability  LoudnessdB  Liveness  Valence  \
46             176      75            67          -4         8       80   
47             100      79            69          -3        17       67   
48             104      70            59          -6        41       50   
49              95      79            75          -6         7       61   

    Length  Acousticness  Speechiness  Popularity  
46     202            24            6          88  
47     214            19            5          88  
48     218            23            3          88  
49     206     

In [42]:
print(df.sample(3))

                            TrackName  ArtistName             Genre  \
5   I Don't Care (with Justin Bieber)  Ed Sheeran               pop   
45                    One Thing Right  Marshmello           brostep   
27                           It's You   Ali Gatie  canadian hip hop   

    BeatsPerMinute  Energy  Danceability  LoudnessdB  Liveness  Valence  \
5              102      68            80          -5         9       84   
45              88      62            66          -2        58       44   
27              96      46            73          -7        19       40   

    Length  Acousticness  Speechiness  Popularity  
5      220             9            4          84  
45     182             7            5          88  
27     213            37            3          89  
